
allprojects {
    // Executed in context of buildscript
    repositories {
        // mavenLocal()
        mavenCentral()
        // jcenter()
        // maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
        gradlePluginPortal()
    }

    apply plugin: 'java'

    dependencies {
        implementation 'com.google.code.findbugs:annotations:3.0.1'

        testImplementation('junit:junit:4.13')
    }

}

for (int i = 0; i < 4; i++) {
    tasks.named('test') {
        dependsOn project(':jarjar-testdata').tasks.named('jar0')
        dependsOn project(':jarjar-testdata').tasks.named('jar1')
        dependsOn project(':jarjar-testdata').tasks.named('jar2')
        dependsOn project(':jarjar-testdata').tasks.named('jar3')
    }
}

