
allprojects {
    // Executed in context of buildscript
    repositories {
        // mavenLocal()
        mavenCentral()
        // jcenter()
        // maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
        gradlePluginPortal()
    }

    apply plugin: 'java'

    dependencies {
        implementation 'com.google.code.findbugs:annotations:3.0.1'

        testImplementation('junit:junit:4.13')
    }

}

project(":jarjar-core").tasks.named('test') {
    (0..3).each { i ->
        dependsOn project(':jarjar-testdata').tasks.named("jar$i")
    }
}

